# Generated by Django 5.1.2 on 2024-10-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Uemail', models.EmailField(max_length=254)),
                ('Upassword', models.CharField(max_length=8)),
            ],
        ),
    ]
