# Generated by Django 5.1.2 on 2024-10-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('U_type', models.CharField(choices=[('student', 'Student'), ('jobHolder', 'Jobholder')], max_length=100, null=True)),
                ('Uemail', models.EmailField(max_length=254)),
                ('Upassword', models.CharField(max_length=8)),
                ('UDate_of_birth', models.DateField(null=True)),
                ('Uage', models.CharField(max_length=100)),
                ('Uimage', models.ImageField(null=True, upload_to='Media/U_pic')),
                ('address', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
